### ISSUE TITLE
 Values inside the Pie Charts ?

### ISSUE THREAD

**Issue by Sharaf-Mansour** [mariusmuntean/ChartJs.Blazor#83] opened 2020-03-17 20:02 UTC
Is there a way to add Data Labels inside the Pie Charts that shows values by default  like this.
![PieCharts](https://user-images.githubusercontent.com/55330747/76896633-dcfc5c80-689a-11ea-88f8-0b4a58a11a01.png)

**Comment by Joelius300** [comment] 2020-03-18 17:31
Thanks for the report but I'm afraid that's a duplicate of #79 :)

**Closed by Joelius300** 2020-03-18 17:31 UTC
Labels: question
