### ISSUE TITLE
Data variable in RadarDataset class to be of type int

### ISSUE THREAD

**Issue by devanshidiaries** [mariusmuntean/ChartJs.Blazor#106] opened 2020-05-01 17:12 UTC
### Describe your question
Data variable in RadarDataset class of the RadarChartComponent is a double type list. Instead of doing a _rand.NextDouble() to assign the chart distribution double values. I would like to give int values for distribution on radar chart. But the Data variable defined in the RadarDataset class only takes a list with double type. Because the RadarDataset class is metadata class from ChartJs.Blazor, I cannot edit this as part of my code. Is there a workaround?

### Which Blazor project type is your question related to?
- Server-Side

### Which charts is this question related to?
Radar Chart

**Comment by Joelius300** [comment] 2020-05-01 17:26
This is a duplicate of #105. I find it incredible that the same question was asked by two different accounts in such a short amount of time. I explained why it's a double in the other issue.  
I'm closing this issue and answering the other because this one was submitted later. Still I want to thank you for providing more information than the other issue.

**Closed by Joelius300** 2020-05-01 17:26 UTC
Labels: duplicate, question
