### ISSUE TITLE
small issue with doughnut chart demo

### ISSUE THREAD

**Issue by 274188A** [mariusmuntean/ChartJs.Blazor#26] opened 2019-06-02 02:14 UTC
https://www.iheartblazor.com/doughnutchart

hit update repeatedly to see what happens...

**Comment by SeppPenner** [comment] 2019-07-22 09:36
If I was you, I would take a look at https://github.com/Joelius300/ChartJSBlazor. This project is maintained at least.

**Comment by Joelius300** [comment] 2019-11-03 14:49
There is no more update-button in the live sample. Does this issue still occur? If so, please add some details on how to reproduce it. Otherwise you can just close this issue :)

**Comment by Joelius300** [comment] 2019-12-10 14:29
Closing this because no response was given after one month. Feel free to reopen if necessary.

**Closed by Joelius300** 2019-12-10 14:29 UTC
