### ISSUE TITLE
Responsive width sizing seems to be broken

### ISSUE THREAD

**Issue by lyptt** [mariusmuntean/ChartJs.Blazor#128] opened 2020-06-09 21:29 UTC
### Describe the bug
When resizing the window to be larger, then shrinking the window again, the canvas element maintains its largest size.

### Which Blazor project type is your bug related to?
- Server-Side

### Which charts does this bug apply to?
all charts

### To Reproduce
1. Using this version of ChartJSBlazor '1.1.0'.
2. Run [this code](https://github.com/mariusmuntean/ChartJs.Blazor#chart) with Responsive = true and MaintainAspectRatio = false
3. Resize window to a large size
4. Resize window to a small size

### Expected behavior
The chart resizes properly to fit its container

### Screenshots
![Capture](https://user-images.githubusercontent.com/346710/84202990-891ba100-aaa0-11ea-9ec7-b08ba44ebb5d.PNG)

### Code example
Please provide full code examples below where possible to make it easier for the developers to check your issues.  
Please also add the working JavaScript equivalent so we can see what you were trying to achieve.
 
```csharp
        _config = new PieConfig
        {
            Options = new PieOptions
            {
                Title = new OptionsTitle
                {
                    Display = true,
                    Text = "Sample chart from Blazor"
                },
                Animation = new ArcAnimation
                {
                    AnimateRotate = true,
                    AnimateScale = true
                },
                Responsive = true,
                MaintainAspectRatio = false
            }
        };

        _config.Data.Labels.AddRange(new[] { "A", "B", "C", "D" });

        var pieSet = new PieDataset
        {
            BackgroundColor = new[] { ColorUtil.RandomColorString(), ColorUtil.RandomColorString(), ColorUtil.RandomColorString(), ColorUtil.RandomColorString() },
            BorderWidth = 0,
            HoverBackgroundColor = ColorUtil.RandomColorString(),
            HoverBorderColor = ColorUtil.RandomColorString(),
            HoverBorderWidth = 1,
            BorderColor = "#ffffff",
        };

        pieSet.Data.AddRange(new double[] { 4, 5, 6, 7 });
        _config.Data.Datasets.Add(pieSet);
```

**Comment by lyptt** [comment] 2020-06-09 21:34
Interestingly, forcing the `row` and `canvas` elements to have 100% width and height fixes things. Maybe this is expected behaviour?

**Comment by swGLS** [comment] 2021-01-13 10:29
It seems that this issueis still open. I am here because I had the exact same problem described here by Iyptt. I couldn't handle scaling a pie chart, sometimes it was blurry, sometimes it disappeared from the screen, the pie chart grew but did not shrink accordingly. So it was a mess. After a day of unsuccessful testing, I decided to take a look at the official chartjs examples. I took a Pie example and looking at the html via the inspector I could see that the only difference with my code was the div wrapper with relative position (as indicated by the chartjs documentation). So simply adding the relative position style into my wrapper, inserting the Chart tag into it **and setting MaintainAspectRatio = false** worked like a charm.
What I mean? From my point of view, I was wrong to use the wrong wrapper. But the library seems to be working perfectly.
So is this still an open issue?

https://user-images.githubusercontent.com/77386190/104440101-39e7a280-5592-11eb-8394-bab61a7fbeac.mp4

**Comment by Joelius300** [comment] 2021-01-24 20:22
This issue is still open because we couldn't find the cause nor a (non-hacky) solution. But the pointer to the relative container might just be it. The fact that you managed to fix it with that is enough for me to close this now. If other people experience the same issue, they should comment below :)

**Closed by Joelius300** 2021-01-24 20:22 UTC
Labels: bug, help wanted

**Comment by FlsZen** [comment] 2021-02-10 04:02
I found myself in a similar situation where the chart wasn't reacting to the narrowing of the window. Wrapping the chart in a `div` similar to what @swGLS mentioned, and similar to what Chart.js docs state, made it become responsive to the width narrowing. To get it to display nicely on my page, I wound up using a wrapper like this:

```
<div style="position: relative; height:350px; width:80%; margin-left: auto; margin-right: auto;">
    <Chart Config="@_chart" />
</div>
```

I'm not sure if there's some general solution that ChartJs.Blazor can provide. Chart.js seems to leave responsiveness up to the developer so this library may also have to pass the responsibility along as well.

**Comment by ryanhalley** [comment] 2024-02-21 18:19
After upgrading from the original NuGet package to the latest fork, I needed the relative position fix to get my barchart to appear at all.

**Comment by ddjerqq** [comment] 2024-04-16 10:09
> Thanks for the detailed report.
> 
> Responsiveness is something we had to fight a few times and it wouldn't surprise me if it still wasn't working correctly. I'll look into it when I get more time.
> 
> FYI, [here](https://www.chartjs.org/docs/latest/general/responsive.html) are the docs for responsiveness with Chart.js.

the link is outdated, [here](https://www.chartjs.org/docs/latest/configuration/responsive.html) is the new one!
